apiVersion: v1
kind: Namespace
metadata:
  name: short-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-app
  namespace: short-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: short-app
  template:
    metadata:
      labels:
        app: short-app
    spec:
      containers:
      - name: short-app
        image: antonlarichev/short-app:v1.4
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"  
          requests:
            memory: "128Mi"
            cpu: "100m"  

---

apiVersion: v1
kind: Service
metadata:
  name: short-app
  namespace: short-app
spec:
  selector:
    app: short-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---

