# tomcat-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: tomcat
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
# tomcat-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat-container
          image: tomcat:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"   # Лимит памяти
              cpu: "500m"       # Лимит CPU
            requests:
              memory: "256Mi"   # Запрос памяти
              cpu: "250m"       # Запрос CPU
          volumeMounts:
            - name: tomcat-html-volume
              mountPath: /usr/local/tomcat/webapps/ROOT
      volumes:
        - name: tomcat-html-volume
          configMap:
            name: tomcat-html-configmap
              
---

# tomcat-ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomcat-ingress
  namespace: tomcat
spec:
  rules:
    - host: tomcat.nazi.today  # Укажите ваш домен
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tomcat-service
                port:
                  number: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-html-configmap
  namespace: tomcat
data:
  server.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My Tomcat Page</title>
    </head>
    <body>
      <h1>Hello from Tomcat!</h1>
    </body>
    </html>
