

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.api.name }}
  namespace:  {{ .Values.app.name }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app:  {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app:  {{ .Values.api.name }}
    spec:
      containers:
      - name:  {{ .Values.api.name }}
        image: {{ .Values.api.containers.image }}
        ports:
        - containerPort: {{ .Values.api.port }}
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.api.name }}-secret
                key: DATABASE_URL
        resources: {{ .Values.api.resources | toYaml | nindent 10 }}

---

apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.api.name }}
  namespace:  {{ .Values.app.name }}
spec:
  selector:
    app:  {{ .Values.api.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  type: ClusterIP

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-secret
  namespace: {{ .Values.app.name }}
type: Opaque
data:
  DATABASE_URL: 'cG9zdGdyZXNxbDovL2RlbW86cG9zdGdyZXMtc2VydmljZTo1NDMyL2RlbW8=' # echo -n postgresql://demo:postgres-service:5432/demo | base64

---

